### ISSUE TITLE
How to flash this code

### ISSUE THREAD

**Issue by mafiaWolf** [espressif/esp8266_mp3_decoder#12]
I've seen this project and I wanna use it but I havent used this ESP8266 before so I dont know how to flash program to this IC.
Could you please tell me how to do that? And, Could I use this code in Module ESP8266 v7, v12?
Thanks for your help

**Comment by Spritetm** [comment]
The mp3-folder has a make.sh file in it. You can use that to build and flash the ESP.

I have no experience with the modules you mention, but the code should work for basically any ESP module that has the required pins brought out.
