### ISSUE TITLE
xtensa-lx106-elf error

### ISSUE THREAD

**Issue by pali24** [espressif/esp8266_mp3_decoder#14]
Hi Spritetm,

It is a super project, I want to try to make it. I built up toolchain, according to: 
https://github.com/esp8266/esp8266-wiki/wiki/Toolchain#install-the-xtensa-crosstool-ng-as-local-user
but if I make it ("make", or "sh make.sh") in folder mp3, I get errors:
/bin/sh: 2: xtensa-lx106-elf-gcc: not found
make: **\* [.subdirs] Error 2

If I tried an example project (blinky), I got an error:
Error calling xtensa-lx106-elf-readelf, do you have Xtensa toolchain in PATH?

Please help me.

**Comment by Spritetm** [comment]
Well, as the blinky example already asks you: do you have the xtensa toolchain in your PATH? Especially
PATH=$PWD/builds/xtensa-lx106-elf/bin:$PATH
is important to execute every time you open a new shell, or put it in your .bashrc.

I'm going to close this as it's not specific to the mp3 decoder code.

**Comment by pali24** [comment]
Thank You, but it did not help :-(
