### ISSUE TITLE
sigma delta modulator Bit 0 always 0

### ISSUE THREAD

**Issue by Xyp** [espressif/esp8266_mp3_decoder#2]
The Bitshift is done at the wrong position. Below a fixed version. 

Fixed code:
static inline int sampToI2sDeltaSigma(short s) {
    int x;
    int val=0;
    int w;
    static int i1v=0, i2v=0;
    static int outReg=0;
    for (x=0; x<32; x++) {
        val<<=1; //next bit ADDED!
        w=s;
        if (outReg>0) w-=32767; else w+=32767; //Difference 1
        w+=i1v; i1v=w; //Integrator 1
        if (outReg>0) w-=32767; else w+=32767; //Difference 2
        w+=i2v; i2v=w; //Integrator 2
        outReg=w;       //register
        if (w>0) val|=1; //comparator
        //val<<=1; //next bit ISSUE: This results in Bit 0 ALWAYS being zero. Bitshift needs to be done upfront
    }
    return val;
}

**Comment by Spritetm** [comment]
Good catch! This indeed is a bug. Weird, normally I'm pretty wary of shift-after-set issues, but this one must've slipped under my radar. Thanks for reporting!
