### ISSUE TITLE
The range of I2S_CLKM_DIV_NUM and I2S_BCK_DIV_NUM

### ISSUE THREAD

**Issue by Simpleyyt** [espressif/esp8266_mp3_decoder#22]
in file `i2s_freertos.c` function `i2sSetRate` writes the range of `I2S_CLKM_DIV_NUM` and `I2S_BCK_DIV_NUM`:

```
I2S_CLKM_DIV_NUM - 5-127
I2S_BCK_DIV_NUM - 2-127
```

However, when I look into the document and found that the bit size of them is both 6, which means the correct range is:

```
I2S_CLKM_DIV_NUM - 5-63
I2S_BCK_DIV_NUM - 2-63
```

right?

**Comment by Spritetm** [comment]
Huh, seems you're right. Fixed in 7552a62d425598d64ebc255d32fa4f20220e92f6
