### ISSUE TITLE
make wifi bridge between phone and mobile

### ISSUE THREAD

**Issue by mkeyno** [espressif/esp8266_mp3_decoder#33]
sorry to open ticket for my question, actually I've plan to make wifi bridge (ESP8266) between my landline phone and my smart mobile , so I could dial or receive my phone by mobile , I'm not sure about the which hardware should be selected and really appreciated to have your probably advise for that

**Comment by Spritetm** [comment]
Sure, but this is far from the place for that. Suggest you find a forum about electronics in general and use that. Closed because offtopic here.
