### ISSUE TITLE
Woking with Nodemcu?

### ISSUE THREAD

**Issue by confile** [espressif/esp8266_mp3_decoder#5]
Does this project also wok with Nodemcu?

http://www.nodemcu.com/index_en.html

**Comment by Spritetm** [comment]
I highly doubt it. The project uses FreeRTOS while NodeMCU (afaik) uses the os-less SDK. Besides that, the MP3 decoder has almost no spare memory to allow NodeMCU to run in.

**Comment by confile** [comment]
@Spritetm is it possible to use a NodeMCU firmware and and some external memory to build a mp3 decoder. Please give me some hint on that.

**Comment by confile** [comment]
@Spritetm Or is there an external decoder module I can use?

**Comment by Spritetm** [comment]
Maybe, if you can convince NodeMCU to put everything it has into external RAM. That's outside the scope of this project, though. And yes, there are a bunch of external MP3 modules available on the market. Choosing one of those also is outside the scope of this project.
