### ISSUE TITLE
FreeRTOS

### ISSUE THREAD

**Issue by steffimueller** [espressif/esp8266_mp3_decoder#6]
Do I have to upload the FreeRTOS firmware first and then upload the ESP8266_MP3_DECODER code?

**Comment by Spritetm** [comment]
Nope, both FreeRTOS and the MP3 decoder are integrated in this project and will be linked into a single binary.

**Comment by confile** [comment]
Is it possible to add additional functionality?

**Comment by Spritetm** [comment]
To what? The software? Sure it is; that's why it's open-source. Keep in mind the system is fairly low on RAM, though.

**Comment by confile** [comment]
I just need to add an external button to start the stream and reconnect the wifi after connection lost. Is this extension possible?

**Comment by Spritetm** [comment]
I see no reason why that would not be possible.
