### ISSUE TITLE
I2S codec

### ISSUE THREAD

**Issue by steffimueller** [espressif/esp8266_mp3_decoder#7]
I want to attach very small speakers (5W) like this: http://www.ebay.com/itm/2pcs-41mm-4Ohm-4-5W-Round-loudspeaker-speaker-treble-tweeter-with-Ear-/151525571265?hash=item2347a0bac1:g:fcIAAOSwg3FUmSU7

To me it is not really clear what the I2S codec is used for and could you please post some alternatives which are smaller and can probably be attached to the same circuit board where the ESP8266 and the SRAM is placed on. Do you have any suggestions for that?

Thank you so much.

**Comment by Spritetm** [comment]
The I2S codec is used as a digital to analog converter. We can't help you with your choice of I2S decoder; we've only tried the one mentioned in the README.md file.
