### ISSUE TITLE
Why not using the I²S interfaces with DMA instead of external I2S codec?

### ISSUE THREAD

**Issue by confile** [espressif/esp8266_mp3_decoder#8]
According to https://en.wikipedia.org/wiki/ESP8266 the ESP8266 has a build in  I²S interfaces with DMA

Why not using the I²S interfaces with DMA instead of external I2S codec?

**Comment by Spritetm** [comment]
Erm, that's what we do. The I2S interface spits out an I2S signal, and you can't listen to that without converting it to an analog signal. Which the I2S codec does.
